CREATE TYPE gender_type AS ENUM ('Female', 'Male');

CREATE TABLE dogs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dog_name TEXT NOT NULL,
    profile_img TEXT NOT NULL,
    gender gender_type,
    age TEXT,
    date_created TIMESTAMP DEFAULT NOW() NOT NULL, 
    arrival_date TIMESTAMP,
    spayedNeutered BOOLEAN NOT NULL, 
    updated_by TEXT,
    tag_number TEXT,
    microchip TEXT
);

