CREATE TYPE gender_type AS ENUM ('Female', 'Male');

CREATE TYPE dog_status AS ENUM ('Adopted', 'Archived', 'Current');

CREATE TABLE dogs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dog_name TEXT NOT NULL,
    profile_img TEXT NOT NULL,
    gender gender_type,
    age TIMESTAMP,
    date_created TIMESTAMP DEFAULT NOW() NOT NULL, 
    arrival_date TIMESTAMP,
    spayedNeutered BOOLEAN NOT NULL, 
    updated_by TEXT,
    tag_number TEXT,
    microchip TEXT,
    dog_status dog_status,
    archive_date TIMESTAMP DEFAULT NOW()
);

