CREATE TYPE shelter_status_type AS ENUM ('current', 'archive');

CREATE TABLE shelter (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  shelter_name TEXT NOT NULL,
  shelter_username TEXT NOT NULL,
  shelter_join_date TIMESTAMP NOT NULL DEFAULT now(),
  shelter_status shelter_status_type,
  shelter_country TEXT NOT NULL,
  shelter_address TEXT NOT NULL,
  shelter_phone TEXT,
  shelter_email TEXT NOT NULL
);

ALTER TABLE users
  ADD COLUMN
    shelter_id INTEGER REFERENCES shelter(id)
    ON DELETE SET NULL;

ALTER TABLE dogs
  ADD COLUMN
    shelter_id INTEGER REFERENCES shelter(id)
    ON DELETE SET NULL;

ALTER TABLE dogs
  ADD COLUMN
    microchip_date TIMESTAMP NOT NULL DEFAULT now();