CREATE TABLE foster (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  foster_date TIMESTAMP NOT NULL DEFAULT now(),
  dog_id INTEGER REFERENCES dogs(id) ON DELETE SET NULL,
  foster_name TEXT NOT NULL,
  foster_email TEXT NOT NULL,
  foster_phone TEXT,
  foster_country TEXT NOT NULL,
  foster_address TEXT,
  contract_url TEXT,
  foster_completed_on TIMESTAMP NOT NULL DEFAULT now()
);